version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/lister-redux/api:v${VERSION}
    ports:
      - "1600:8400"
    restart: always
    depends_on:
      - mongodb
    environment:
      - GOOS=${GOOS}
      - GOARCH=${GOARCH}
      - PORT=${PORT}
      - LOGLEVEL=info
      - LOGFILE=/root/log/lister.log
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - VERSION=v${VERSION}
    volumes:
      - /var/log:/root/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - poptape

  mongodb:
    image: mongo:latest
    restart: always
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    ports:
      - "1601:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes: 
      - poptape_lister_data:/data/db
    networks:
      - poptape

networks:
  poptape:
    external: true

volumes:
  poptape_lister_data:
    name: poptape_lister_data