services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/lister-redux/api:v${VERSION}
    ports:
      - "1600:8400"
    restart: no
    depends_on:
      - mongodb
    environment:
      - "GOOS=${GOOS}"
      - "GOARCH=${GOARCH}"
      - "PORT=${PORT}"
#      - LOGLEVEL={$LOGLEVEL}
#      - LOGFILE={$LOGFILE}
#      - MONGO_HOST=mongodb
#      - MONGO_PORT=27017
#      - MONGO_USERNAME=${MONGO_USERNAME}
#      - MONGO_PASSWORD=${MONGO_PASSWORD}
#      - MONGO_DATABASE=${MONGO_DATABASE}
#      - VERSION=v${VERSION}
    volumes:
      - ${LOCAL_LOG_LOC}:/lister/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - poptape

  mongodb:
    image: mongo:latest
    restart: always
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    ports:
      - "1601:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes: 
      - poptape_lister_data:/data/db
    networks:
      - poptape

networks:
  poptape:
    external: true

volumes:
  poptape_lister_data:
    name: poptape_lister_data