name: Build app & run testsuite
permissions:
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 11 * * 1' # run "At 11:00 on Monday"

jobs:
  all-tests:
    runs-on: ubuntu-latest
    name: Run testsuite
    services:
      # label used to access the service container
      mongodb:
        # dockerhub image
        image: mongo:latest
        # provide the login and db deets for mongo
        command:
          - --storageEngine
          - wiredTiger
          - --auth
        ports:
          - "1601:27017"
        environment:
          MONGO_INITDB_ROOT_USERNAME: lister_test
          MONGO_INITDB_ROOT_PASSWORD: "${{ secrets.TESTDB_PASSWORD }}"
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: go mod tidy

      - name: Run unit tests and generate coverage
        run: |
          go test -v -covermode=atomic -coverprofile=coverage.out ./...

      - name: Check coverage threshold (90%)
        run: |
          coverage=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Total coverage: $coverage"
          cov_int=${coverage%.*}
          if [ "$cov_int" -lt 40 ]; then
            echo "Coverage $coverage is below 40%"
            exit 1
          fi

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out